"""Independent checks for tensor weak momentum and constrained projection."""

import jax
import jax.numpy as jnp
import numpy as np
import pytest
import scipy.linalg as la

from bspf_models.fluids.weak_navier_stokes import plan_weak_navier_stokes2d
from bspf_models.fluids.weak_navier_stokes import weak_ns_project
from bspf_models.fluids.weak_navier_stokes import weak_ns_divergence
from bspf_models.fluids.weak_navier_stokes import weak_ns_momentum_load
from bspf_models.fluids.weak_navier_stokes import weak_ns_rhs
from bspf_models.fluids.weak_navier_stokes import weak_ns_helmholtz
from bspf_models.fluids.weak_navier_stokes import weak_ns_rk4_step
from bspf_models.fluids.weak_navier_stokes import weak_ns_load


jax.config.update("jax_enable_x64", True)


@pytest.fixture(scope="module")
def plan():
    pytest.importorskip("gmpy2")
    return plan_weak_navier_stokes2d(
        np.linspace(-1, 1, 12),
        np.linspace(-1, 1, 13),
        q=3,
        degree=5,
        n_basis=8,
        window=6,
        modes=5,
    )


def test_projection_matches_independent_dense_nullspace(plan):
    x, y = plan.x, plan.y
    nx, ny = len(x.x), len(y.x)
    # Independently integrate the full pressure tests against velocity gradient.
    bx, by = np.asarray(x.values), np.asarray(y.values)
    gx, gy = np.asarray(x.gradients), np.asarray(y.gradients)
    sx = bx.T @ (np.asarray(x.weights)[:, None] * bx[:, 1:-1])
    sy = by.T @ (np.asarray(y.weights)[:, None] * by[:, 1:-1])
    cx = bx.T @ (np.asarray(x.weights)[:, None] * gx[:, 1:-1])
    cy = by.T @ (np.asarray(y.weights)[:, None] * gy[:, 1:-1])
    d = np.column_stack((np.kron(cx, sy), np.kron(sx, cy)))
    inv = np.kron(x.inverse_root, y.inverse_root)
    inv = la.block_diag(inv, inv)
    z = la.null_space(d @ inv, rcond=1e-11)
    raw = np.random.default_rng(1).normal(size=(nx, ny, 2))
    f = np.concatenate((raw[1:-1, 1:-1, 0].ravel(), raw[1:-1, 1:-1, 1].ravel()))
    expected = inv @ z @ z.T @ la.solve(inv, f)
    actual = np.asarray(jax.jit(weak_ns_project)(plan, jnp.asarray(raw)))
    got = np.concatenate((actual[1:-1, 1:-1, 0].ravel(), actual[1:-1, 1:-1, 1].ravel()))
    np.testing.assert_allclose(got, expected, atol=2e-11)
    assert np.max(abs(weak_ns_divergence(plan, actual))) < 1e-10
    np.testing.assert_allclose(weak_ns_project(plan, actual), actual, atol=2e-12)
    assert np.max(abs(actual[[0, -1]])) == 0
    assert np.max(abs(actual[:, [0, -1]])) == 0


def test_projected_nonlinear_energy_law(plan):
    raw = np.random.default_rng(5).normal(size=(len(plan.x.x), len(plan.y.x), 2))
    u = weak_ns_project(plan, jnp.asarray(raw))
    rhs = weak_ns_rhs(plan, u)
    mx = np.asarray(plan.x.mass_rows[:, 1:-1])
    my = np.asarray(plan.y.mass_rows[:, 1:-1])
    kx = np.asarray(plan.x.stiffness_rows[:, 1:-1])
    ky = np.asarray(plan.y.stiffness_rows[:, 1:-1])
    rate = 0.0
    loss = 0.0
    for c in range(2):
        v = np.asarray(u[1:-1, 1:-1, c])
        a = np.asarray(rhs[1:-1, 1:-1, c])
        rate += np.sum(v * (mx @ a @ my))
        loss -= float(plan.viscosity) * np.sum(v * (kx @ v @ my + mx @ v @ ky))
    np.testing.assert_allclose(rate, loss, atol=2e-12, rtol=2e-12)
    assert rate < 0
    updated = jax.jit(weak_ns_rk4_step)(plan, u, 1e-4)
    assert np.max(abs(weak_ns_divergence(plan, updated))) < 1e-10


def test_helmholtz_matches_dense(plan):
    x, y = plan.x, plan.y
    mx, my = np.asarray(x.mass_rows[:, 1:-1]), np.asarray(y.mass_rows[:, 1:-1])
    kx, ky = (
        np.asarray(x.stiffness_rows[:, 1:-1]),
        np.asarray(y.stiffness_rows[:, 1:-1]),
    )
    load = np.random.default_rng(2).normal(size=(len(mx), len(my)))
    alpha, beta = 1.7, 0.03
    matrix = alpha * np.kron(mx, my) + beta * (np.kron(kx, my) + np.kron(mx, ky))
    expected = la.solve(matrix, load.ravel(), assume_a="pos").reshape(load.shape)
    np.testing.assert_allclose(
        weak_ns_helmholtz(plan, load, alpha=alpha, beta=beta),
        expected,
        atol=5e-12,
        rtol=1e-12,
    )


def test_polynomial_diffusion_and_constant_flow(plan):
    # A constant velocity has zero momentum load for interior test functions.
    u = jnp.ones((len(plan.x.x), len(plan.y.x), 2))
    assert np.max(abs(weak_ns_momentum_load(plan, u))) < 1e-11
    # Mass and stiffness independently reproduce integration of a polynomial.
    for line in (plan.x, plan.y):
        values = 1 - np.asarray(line.x) ** 2
        force = line.values[:, 1:-1].T @ (line.weights * 2)
        np.testing.assert_allclose(line.stiffness_rows @ values, force, atol=1e-11)


def test_continuous_pressure_gradient_is_removed(plan):
    # Exact p=x+2y, not a pressure generated by the discrete Schur matrix.
    force = jnp.ones((len(plan.x.weights), len(plan.y.weights), 2))
    force = force.at[..., 1].set(2.)
    zero = jnp.zeros((len(plan.x.x), len(plan.y.x), 2))
    acceleration = weak_ns_rhs(plan, zero, weak_ns_load(plan, force))
    assert np.max(abs(acceleration)) < 2e-11
