"""Analytic layer moments and fixed-budget checks for scaled ray quadrature."""
import argparse
import json
from pathlib import Path
from math import comb,gamma
import numpy as np
from scipy.special import gammainc
from bspf_models.elliptic.immersed_poisson import EllipticHole
from scaled_response_quadrature import boundary_rays,scaled_channel_quadrature


def exact_moment(bounds,hole,p,q):
    left,right,h=bounds;cx,cy=hole.center;a,b=hole.axes
    rectangle=(right**(p+1)-left**(p+1))/(p+1)*(h**(q+1)-(-h)**(q+1))/(q+1)
    ellipse=0.
    for i in range(0,p+1,2):
        for j in range(0,q+1,2):
            disk=gamma((i+1)/2)*gamma((j+1)/2)/gamma((i+j)/2+2)
            ellipse+=comb(p,i)*comb(q,j)*cx**(p-i)*cy**(q-j)*a**(i+1)*b**(j+1)*disk
    return rectangle-ellipse


def main():
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--out',type=Path,required=True)
    ap.add_argument('--layer-order',type=int,default=48)
    ap.add_argument('--bulk-order',type=int,default=32)
    args=ap.parse_args();args.out.mkdir(parents=True,exist_ok=True)
    bounds=(-1,5,1);hole=EllipticHole();rows=[]
    rays,tw,cross,normal=boundary_rays(bounds,hole,73,33)
    rmax=np.linalg.norm(rays/np.asarray(hole.axes),axis=1)
    minor=min(hole.axes);H=minor*(rmax-1)
    for re in [20,200,2000,20000]:
        ell=np.sqrt(.01*(2/3)*.46/re)
        lengths=ell*np.array([.5,1,2,4])
        points,w=scaled_channel_quadrature(bounds,hole,73,33,layer_lengths=lengths,
                                           layer_order=args.layer_order,bulk_order=args.bulk_order)
        assert np.all(w>0) and np.all(hole.level(points)>=1)
        max_moment=0.
        for p in range(5):
            for q in range(5-p):
                actual=w@(points[:,0]**p*points[:,1]**q)
                exact=exact_moment(bounds,hole,p,q)
                max_moment=max(max_moment,abs(actual-exact)/max(1,abs(exact)))
        d=minor*(np.linalg.norm((points-hole.center)/hole.axes,axis=1)-1)
        errors=[]
        # Exact radial antiderivatives; only the common tangential rule remains.
        # Includes exponential scales narrower than the smallest basis length,
        # as generated by products of derivatives in energy/nonlinear terms.
        for length in lengths:
            for power,rate in [(0,1),(2,1),(0,2),(2,2),(4,2),(0,3)]:
                s=length/rate
                def lower(k):return gamma(k+1)*gammainc(k+1,H/s)
                radial=(s**(power+1)/minor*lower(power)+s**(power+2)/minor**2*lower(power+1))/length**power
                exact=float(tw@(cross/rmax**2*radial))
                actual=float(w@((d/length)**power*np.exp(-rate*d/length)))
                errors.append(abs(actual-exact)/abs(exact))
        row=dict(reynolds=re,points=len(w),area=float(w.sum()),
                 maximum_polynomial_moment_error=max_moment,
                 maximum_relative_layer_moment_error=max(errors))
        rows.append(row);print(json.dumps(row),flush=True)
        # Retain coordinates for reproducible layout inspection.
        np.savez_compressed(args.out/f'quadrature_re{re}.npz',points=points,weights=w,lengths=lengths)
    assert len(set(r['points'] for r in rows))==1
    (args.out/'moments.json').write_text(json.dumps(rows,indent=2)+'\n')
    assert max(r['maximum_polynomial_moment_error'] for r in rows)<1e-10
    assert max(r['maximum_relative_layer_moment_error'] for r in rows)<1e-7


if __name__=='__main__':main()
